name: build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: '${{ secrets.QUAYIO_USERNAME }}'
          password: '${{ secrets.QUAYIO_PASSWORD }}'
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t quay.io/wish/aws-csm-exporter:${GITHUB_REF##*/} \
            -t ghcr.io/wish/aws-csm-exporter:${GITHUB_REF##*/} \
            --push .

